#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=4
TOTAL_MINUTES=10

OLD_PREVIEW="https://marketing-teacher-workspace-ig1d8hxuy-wondopamines-projects.vercel.app"
STALE_PREVIEW="https://marketing-teacher-workspace-f2lnd28t1-wondopamines-projects.vercel.app"
REPO="wondopamine/marketing-teacher-workspace"

http_code() { curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$1" 2>/dev/null || printf '000'; }

banner "Review link — public access + feedback sending"

# ── Stage 1: make the link public ─────────────────────────────────────────
stage "Vercel — switch off login on the review link" 2
say "Right now every deployment answers with a Vercel login page (HTTP 302)."
say "One dashboard toggle makes the links open for anyone."
open_url "https://vercel.com/wondopamines-projects/marketing-teacher-workspace/settings/deployment-protection"
step "Find the 'Vercel Authentication' card."
step "Set it to 'Disabled' (or toggle 'Standard Protection' off)."
step "Click Save."
pause "Done? Press Enter and I'll check the link…"
while true; do
  code=$(http_code "$OLD_PREVIEW/content-review")
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s the review link now opens without a login (HTTP 200)\n' "$GREEN" "$RESET"
    break
  fi
  warn "still getting HTTP $code (expected 200). The save may take a few seconds."
  if ! confirm "Check again?"; then
    SKIPPED+=("Vercel Authentication still on — links stay login-walled")
    break
  fi
done

# ── Stage 2: mint the GitHub token ─────────────────────────────────────────
stage "GitHub — a token so Send can reach your repo" 4
say "A fine-grained token lets the review page commit feedback to YOUR fork —"
say "one repository, contents + pull requests, nothing else."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: tw-review-feedback   ·   Expiration: 30 days."
step "Resource owner: wondopamine."
step "Repository access: 'Only select repositories' → $REPO."
step "Permissions → Repository permissions:"
step "   Contents: Read and write"
step "   Pull requests: Read and write"
step "Click 'Generate token' and copy it (starts github_pat_)."
while true; do
  ask_secret REVIEW_GITHUB_TOKEN "Paste the token:"
  repo_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 \
    -H "Authorization: Bearer $REVIEW_GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/$REPO" 2>/dev/null || printf '000')
  contents_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 \
    -H "Authorization: Bearer $REVIEW_GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/$REPO/contents/README.md" 2>/dev/null || printf '000')
  pulls_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 \
    -H "Authorization: Bearer $REVIEW_GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/$REPO/pulls?state=open" 2>/dev/null || printf '000')
  if [[ "$repo_code" == "200" && "$contents_code" == "200" && "$pulls_code" == "200" ]]; then
    printf '  %s✓%s token verified — it can read the repo, its contents, and its pull requests\n' "$GREEN" "$RESET"
    break
  fi
  warn "token check failed (repo=$repo_code contents=$contents_code pulls=$pulls_code)."
  note "A 404 usually means the wrong repository was selected; 401 means a bad paste."
  if ! confirm "Paste it again?"; then
    SKIPPED+=("GitHub token unverified — Send may fail on the deployed page")
    break
  fi
done
write_env REVIEW_GITHUB_REPO "$REPO"

# ── Stage 3: put both values on Vercel (preview env) ──────────────────────
stage "Vercel — store the two values for preview deployments" 1
say "Adding REVIEW_GITHUB_TOKEN and REVIEW_GITHUB_REPO to the preview environment."
note "(Preview only — the decision record forbids deploying this route to production.)"
vercel env rm REVIEW_GITHUB_TOKEN preview -y >/dev/null 2>&1 || true
vercel env rm REVIEW_GITHUB_REPO  preview -y >/dev/null 2>&1 || true
if printf '%s' "$REVIEW_GITHUB_TOKEN" | vercel env add REVIEW_GITHUB_TOKEN preview >/dev/null 2>&1; then
  printf '  %s✓%s REVIEW_GITHUB_TOKEN → Vercel (preview)\n' "$GREEN" "$RESET"
else
  SKIPPED+=("vercel env add REVIEW_GITHUB_TOKEN preview — run it by hand")
  warn "could not store the token on Vercel"
fi
if printf '%s' "$REPO" | vercel env add REVIEW_GITHUB_REPO preview >/dev/null 2>&1; then
  printf '  %s✓%s REVIEW_GITHUB_REPO → Vercel (preview)\n' "$GREEN" "$RESET"
else
  SKIPPED+=("vercel env add REVIEW_GITHUB_REPO preview — run it by hand")
  warn "could not store the repo name on Vercel"
fi

# ── Stage 4: deploy and prove it works logged-out ──────────────────────────
stage "Deploy — a fresh preview with sending switched on" 3
say "Deploying…"
NEW_URL=$(vercel deploy 2>/tmp/review-wizard-deploy.log || true)
if [[ -z "$NEW_URL" || "$NEW_URL" != https://* ]]; then
  warn "deploy did not return a URL — see /tmp/review-wizard-deploy.log"
  SKIPPED+=("vercel deploy failed — deploy by hand, then share <url>/content-review")
else
  printf '  %s✓ deployed%s %s\n' "$GREEN" "$RESET" "$NEW_URL"
  say "Checking it opens without a login…"
  code=$(http_code "$NEW_URL/content-review")
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s HTTP 200 — no login wall\n' "$GREEN" "$RESET"
  else
    warn "got HTTP $code — if protection was just disabled, wait a moment and re-check"
    SKIPPED+=("verify $NEW_URL/content-review returns 200")
  fi
  if curl -s --max-time 20 "$NEW_URL/content-review" 2>/dev/null | grep -q "See what is changing. Know what to do next."; then
    printf '  %s✓%s the seven-part GA narrative is live on this preview\n' "$GREEN" "$RESET"
  fi
  write_env REVIEW_SHARE_URL "$NEW_URL/content-review"
  printf '\n  %sShare this link with reviewers:%s\n' "$BOLD" "$RESET"
  printf '  %s%s/content-review%s\n\n' "$GREEN" "$NEW_URL" "$RESET"
  if confirm "Retire the two older previews (one shows the outdated story)?"; then
    vercel remove "$OLD_PREVIEW"   -y >/dev/null 2>&1 && printf '  %s✓ retired%s %s\n' "$GREEN" "$RESET" "$OLD_PREVIEW" || warn "could not remove $OLD_PREVIEW"
    vercel remove "$STALE_PREVIEW" -y >/dev/null 2>&1 && printf '  %s✓ retired%s %s\n' "$GREEN" "$RESET" "$STALE_PREVIEW" || warn "could not remove $STALE_PREVIEW"
  else
    SKIPPED+=("retire superseded previews: $OLD_PREVIEW and $STALE_PREVIEW")
  fi
fi

finish
say "Last check, on the new link in a private/incognito window:"
step "change one headline → Enter → Send"
step "a pull request titled 'Landing page review feedback' appears on $REPO"
say ""
