/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsPreviewRouteImport } from './routes/cms-preview'
import { Route as ContentReviewRouteImport } from './routes/content-review'
import { Route as ApiCmsCommentsRouteImport } from './routes/api/cms/comments'
import { Route as ApiCmsSessionRouteImport } from './routes/api/cms/session'
import { Route as ApiCmsVersionsRouteImport } from './routes/api/cms/versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsPreviewRoute = CmsPreviewRouteImport.update({
  id: '/cms-preview',
  path: '/cms-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentReviewRoute = ContentReviewRouteImport.update({
  id: '/content-review',
  path: '/content-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsCommentsRoute = ApiCmsCommentsRouteImport.update({
  id: '/api/cms/comments',
  path: '/api/cms/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsSessionRoute = ApiCmsSessionRouteImport.update({
  id: '/api/cms/session',
  path: '/api/cms/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsVersionsRoute = ApiCmsVersionsRouteImport.update({
  id: '/api/cms/versions',
  path: '/api/cms/versions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/content-review': typeof ContentReviewRoute
  '/api/cms/comments': typeof ApiCmsCommentsRoute
  '/api/cms/session': typeof ApiCmsSessionRoute
  '/api/cms/versions': typeof ApiCmsVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/content-review': typeof ContentReviewRoute
  '/api/cms/comments': typeof ApiCmsCommentsRoute
  '/api/cms/session': typeof ApiCmsSessionRoute
  '/api/cms/versions': typeof ApiCmsVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/content-review': typeof ContentReviewRoute
  '/api/cms/comments': typeof ApiCmsCommentsRoute
  '/api/cms/session': typeof ApiCmsSessionRoute
  '/api/cms/versions': typeof ApiCmsVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms-preview'
    | '/content-review'
    | '/api/cms/comments'
    | '/api/cms/session'
    | '/api/cms/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cms-preview'
    | '/content-review'
    | '/api/cms/comments'
    | '/api/cms/session'
    | '/api/cms/versions'
  id:
    | '__root__'
    | '/'
    | '/cms-preview'
    | '/content-review'
    | '/api/cms/comments'
    | '/api/cms/session'
    | '/api/cms/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsPreviewRoute: typeof CmsPreviewRoute
  ContentReviewRoute: typeof ContentReviewRoute
  ApiCmsCommentsRoute: typeof ApiCmsCommentsRoute
  ApiCmsSessionRoute: typeof ApiCmsSessionRoute
  ApiCmsVersionsRoute: typeof ApiCmsVersionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms-preview': {
      id: '/cms-preview'
      path: '/cms-preview'
      fullPath: '/cms-preview'
      preLoaderRoute: typeof CmsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-review': {
      id: '/content-review'
      path: '/content-review'
      fullPath: '/content-review'
      preLoaderRoute: typeof ContentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/comments': {
      id: '/api/cms/comments'
      path: '/api/cms/comments'
      fullPath: '/api/cms/comments'
      preLoaderRoute: typeof ApiCmsCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/session': {
      id: '/api/cms/session'
      path: '/api/cms/session'
      fullPath: '/api/cms/session'
      preLoaderRoute: typeof ApiCmsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/versions': {
      id: '/api/cms/versions'
      path: '/api/cms/versions'
      fullPath: '/api/cms/versions'
      preLoaderRoute: typeof ApiCmsVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsPreviewRoute: CmsPreviewRoute,
  ContentReviewRoute: ContentReviewRoute,
  ApiCmsCommentsRoute: ApiCmsCommentsRoute,
  ApiCmsSessionRoute: ApiCmsSessionRoute,
  ApiCmsVersionsRoute: ApiCmsVersionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
