export type AttentionTag = "FAS" | "SwAN" | "LSM" | "LSP" | "TCI"

export type Trend = "improving" | "declining" | "stable"

export type Student = {
  id: string
  name: string
  classCode: string
  cca: string
  attentionTags: Array<AttentionTag>
  attendancePct: number
  lateComingPct: number
  nonVrAbsencesPct: number
  ccaAttendancePct: number
  academicsPct: number
  tciRiskIndicators: number
  offences: number
  counsellingCases: number
  conductGrade: "Excellent" | "Good" | "Fair" | "Poor"
  attendanceTrend: Trend
  academicsTrend: Trend
  wellbeingTrend: Trend
  primaryContactName: string
}

export type ClassFixture = {
  id: string
  label: string
  classCode: string
  attendancePct: number
  attendanceTrend: Trend
  lateComingCount: number
  lateComingTrend: Trend
  studentsNeedingSupport: number
  supportTrend: Trend
}

export const CCA_OPTIONS = [
  "Basketball",
  "Badminton",
  "Volleyball",
  "Football",
  "Choir",
  "Concert Band",
  "Drama",
  "Robotics",
  "Art Club",
] as const

const SECONDARY_3: Array<Student> = [
  {
    id: "s3-01",
    name: "Chen Jun Kai",
    classCode: "3A",
    cca: "Basketball",
    attentionTags: ["FAS"],
    attendancePct: 42,
    lateComingPct: 0,
    nonVrAbsencesPct: 8,
    ccaAttendancePct: 80,
    academicsPct: 62,
    tciRiskIndicators: 3,
    offences: 3,
    counsellingCases: 2,
    conductGrade: "Poor",
    attendanceTrend: "declining",
    academicsTrend: "stable",
    wellbeingTrend: "improving",
    primaryContactName: "Mrs Chen (Mother)",
  },
  {
    id: "s3-02",
    name: "Vincent Koh Xin Yi",
    classCode: "3A",
    cca: "Badminton",
    attentionTags: [],
    attendancePct: 91,
    lateComingPct: 2,
    nonVrAbsencesPct: 3,
    ccaAttendancePct: 92,
    academicsPct: 78,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Koh (Father)",
  },
  {
    id: "s3-03",
    name: "Lam Wei Jie",
    classCode: "3A",
    cca: "Volleyball",
    attentionTags: ["SwAN"],
    attendancePct: 76,
    lateComingPct: 4,
    nonVrAbsencesPct: 5,
    ccaAttendancePct: 88,
    academicsPct: 71,
    tciRiskIndicators: 1,
    offences: 1,
    counsellingCases: 1,
    conductGrade: "Good",
    attendanceTrend: "improving",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Lam (Mother)",
  },
  {
    id: "s3-04",
    name: "Sarah Chan Jun Kai",
    classCode: "3A",
    cca: "Football",
    attentionTags: [],
    attendancePct: 88,
    lateComingPct: 1,
    nonVrAbsencesPct: 2,
    ccaAttendancePct: 95,
    academicsPct: 82,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Chan (Father)",
  },
  {
    id: "s3-05",
    name: "Kenneth Koh Xin Yi",
    classCode: "3A",
    cca: "Choir",
    attentionTags: ["LSM", "LSP"],
    attendancePct: 67,
    lateComingPct: 8,
    nonVrAbsencesPct: 6,
    ccaAttendancePct: 72,
    academicsPct: 58,
    tciRiskIndicators: 2,
    offences: 2,
    counsellingCases: 1,
    conductGrade: "Fair",
    attendanceTrend: "declining",
    academicsTrend: "declining",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Koh (Mother)",
  },
  {
    id: "s3-06",
    name: "Liang Wei Jie",
    classCode: "3A",
    cca: "Concert Band",
    attentionTags: [],
    attendancePct: 84,
    lateComingPct: 3,
    nonVrAbsencesPct: 4,
    ccaAttendancePct: 90,
    academicsPct: 74,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Good",
    attendanceTrend: "stable",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Liang (Father)",
  },
  {
    id: "s3-07",
    name: "Sarah Tan Jun Kai",
    classCode: "3A",
    cca: "Drama",
    attentionTags: [],
    attendancePct: 79,
    lateComingPct: 5,
    nonVrAbsencesPct: 3,
    ccaAttendancePct: 86,
    academicsPct: 69,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Good",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "improving",
    primaryContactName: "Mrs Tan (Mother)",
  },
  {
    id: "s3-08",
    name: "Marcus Lim Wei Sheng",
    classCode: "3B",
    cca: "Basketball",
    attentionTags: ["TCI"],
    attendancePct: 55,
    lateComingPct: 12,
    nonVrAbsencesPct: 9,
    ccaAttendancePct: 70,
    academicsPct: 51,
    tciRiskIndicators: 4,
    offences: 4,
    counsellingCases: 2,
    conductGrade: "Fair",
    attendanceTrend: "declining",
    academicsTrend: "declining",
    wellbeingTrend: "declining",
    primaryContactName: "Mrs Lim (Mother)",
  },
  {
    id: "s3-09",
    name: "Priya Subramanian",
    classCode: "3B",
    cca: "Robotics",
    attentionTags: [],
    attendancePct: 95,
    lateComingPct: 0,
    nonVrAbsencesPct: 1,
    ccaAttendancePct: 98,
    academicsPct: 89,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Subramanian (Mother)",
  },
  {
    id: "s3-10",
    name: "Aisha Rahman",
    classCode: "3B",
    cca: "Art Club",
    attentionTags: ["LSP"],
    attendancePct: 81,
    lateComingPct: 4,
    nonVrAbsencesPct: 4,
    ccaAttendancePct: 84,
    academicsPct: 66,
    tciRiskIndicators: 1,
    offences: 0,
    counsellingCases: 1,
    conductGrade: "Good",
    attendanceTrend: "improving",
    academicsTrend: "improving",
    wellbeingTrend: "improving",
    primaryContactName: "Mr Rahman (Father)",
  },
  {
    id: "s3-11",
    name: "Daniel Ng Jun Wei",
    classCode: "3B",
    cca: "Football",
    attentionTags: [],
    attendancePct: 87,
    lateComingPct: 2,
    nonVrAbsencesPct: 3,
    ccaAttendancePct: 91,
    academicsPct: 76,
    tciRiskIndicators: 0,
    offences: 1,
    counsellingCases: 0,
    conductGrade: "Good",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Ng (Father)",
  },
  {
    id: "s3-12",
    name: "Mei Ling Tan",
    classCode: "3B",
    cca: "Volleyball",
    attentionTags: ["FAS"],
    attendancePct: 63,
    lateComingPct: 9,
    nonVrAbsencesPct: 7,
    ccaAttendancePct: 75,
    academicsPct: 60,
    tciRiskIndicators: 2,
    offences: 1,
    counsellingCases: 2,
    conductGrade: "Fair",
    attendanceTrend: "declining",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Tan (Mother)",
  },
]

const SECONDARY_2: Array<Student> = [
  {
    id: "s2-01",
    name: "Brian Toh Wei Han",
    classCode: "2A",
    cca: "Basketball",
    attentionTags: [],
    attendancePct: 92,
    lateComingPct: 1,
    nonVrAbsencesPct: 2,
    ccaAttendancePct: 95,
    academicsPct: 80,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Toh (Mother)",
  },
  {
    id: "s2-02",
    name: "Rachel Goh Mei Lin",
    classCode: "2A",
    cca: "Choir",
    attentionTags: ["SwAN"],
    attendancePct: 73,
    lateComingPct: 6,
    nonVrAbsencesPct: 5,
    ccaAttendancePct: 78,
    academicsPct: 64,
    tciRiskIndicators: 1,
    offences: 0,
    counsellingCases: 1,
    conductGrade: "Good",
    attendanceTrend: "improving",
    academicsTrend: "improving",
    wellbeingTrend: "improving",
    primaryContactName: "Mr Goh (Father)",
  },
  {
    id: "s2-03",
    name: "Hafiz Ismail",
    classCode: "2A",
    cca: "Football",
    attentionTags: [],
    attendancePct: 86,
    lateComingPct: 3,
    nonVrAbsencesPct: 3,
    ccaAttendancePct: 89,
    academicsPct: 72,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Good",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Ismail (Mother)",
  },
  {
    id: "s2-04",
    name: "Sophia Lee Hui Ying",
    classCode: "2B",
    cca: "Drama",
    attentionTags: ["LSM"],
    attendancePct: 70,
    lateComingPct: 7,
    nonVrAbsencesPct: 5,
    ccaAttendancePct: 80,
    academicsPct: 65,
    tciRiskIndicators: 1,
    offences: 1,
    counsellingCases: 1,
    conductGrade: "Fair",
    attendanceTrend: "stable",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Lee (Mother)",
  },
  {
    id: "s2-05",
    name: "Joshua Tay Jun Hong",
    classCode: "2B",
    cca: "Robotics",
    attentionTags: [],
    attendancePct: 96,
    lateComingPct: 0,
    nonVrAbsencesPct: 1,
    ccaAttendancePct: 99,
    academicsPct: 91,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Tay (Father)",
  },
]

const SECONDARY_4: Array<Student> = [
  {
    id: "s4-01",
    name: "Wei Xin Tan",
    classCode: "4A",
    cca: "Concert Band",
    attentionTags: [],
    attendancePct: 89,
    lateComingPct: 1,
    nonVrAbsencesPct: 2,
    ccaAttendancePct: 93,
    academicsPct: 84,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Excellent",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Tan (Mother)",
  },
  {
    id: "s4-02",
    name: "Ravi Kumar",
    classCode: "4A",
    cca: "Football",
    attentionTags: ["TCI"],
    attendancePct: 58,
    lateComingPct: 14,
    nonVrAbsencesPct: 11,
    ccaAttendancePct: 65,
    academicsPct: 49,
    tciRiskIndicators: 5,
    offences: 5,
    counsellingCases: 3,
    conductGrade: "Poor",
    attendanceTrend: "declining",
    academicsTrend: "declining",
    wellbeingTrend: "declining",
    primaryContactName: "Mr Kumar (Father)",
  },
  {
    id: "s4-03",
    name: "Emily Wong Pei Shan",
    classCode: "4A",
    cca: "Art Club",
    attentionTags: ["LSP"],
    attendancePct: 82,
    lateComingPct: 4,
    nonVrAbsencesPct: 4,
    ccaAttendancePct: 85,
    academicsPct: 70,
    tciRiskIndicators: 1,
    offences: 0,
    counsellingCases: 1,
    conductGrade: "Good",
    attendanceTrend: "improving",
    academicsTrend: "improving",
    wellbeingTrend: "stable",
    primaryContactName: "Mrs Wong (Mother)",
  },
  {
    id: "s4-04",
    name: "Jia Hao Lim",
    classCode: "4A",
    cca: "Basketball",
    attentionTags: [],
    attendancePct: 91,
    lateComingPct: 1,
    nonVrAbsencesPct: 2,
    ccaAttendancePct: 94,
    academicsPct: 79,
    tciRiskIndicators: 0,
    offences: 0,
    counsellingCases: 0,
    conductGrade: "Good",
    attendanceTrend: "stable",
    academicsTrend: "stable",
    wellbeingTrend: "stable",
    primaryContactName: "Mr Lim (Father)",
  },
]

export const CLASSES: Array<ClassFixture & { students: Array<Student> }> = [
  {
    id: "sec-2",
    label: "Secondary 2",
    classCode: "2A",
    attendancePct: 81,
    attendanceTrend: "stable",
    lateComingCount: 3,
    lateComingTrend: "stable",
    studentsNeedingSupport: 7,
    supportTrend: "improving",
    students: SECONDARY_2,
  },
  {
    id: "sec-3",
    label: "Secondary 3",
    classCode: "3A",
    attendancePct: 34,
    attendanceTrend: "declining",
    lateComingCount: 5,
    lateComingTrend: "improving",
    studentsNeedingSupport: 17,
    supportTrend: "stable",
    students: SECONDARY_3,
  },
  {
    id: "sec-4",
    label: "Secondary 4",
    classCode: "4A",
    attendancePct: 78,
    attendanceTrend: "improving",
    lateComingCount: 2,
    lateComingTrend: "stable",
    studentsNeedingSupport: 4,
    supportTrend: "improving",
    students: SECONDARY_4,
  },
]

export const DEFAULT_CLASS_ID = "sec-3"

export function getClassById(id: string) {
  return CLASSES.find((c) => c.id === id) ?? CLASSES[1]
}
